export const queryKeys = {
  settings: {
    all: ['settings'] as const,
    tasks: ['settings', 'tasks'] as const,
  },
  account: {
    all: ['account'] as const,
  },
  links: {
    all: ['links'] as const,
    counts: (appId: string, recordId: string) => ['links', 'counts', appId, recordId] as const,
    details: (appId: string, recordId: string) => ['links', 'details', appId, recordId] as const,
  },
  search: {
    global: (q: string) => ['search', 'global', q] as const,
  },
  docs: {
    all: ['docs'] as const,
    list: ['docs', 'list'] as const,
    tree: ['docs', 'tree'] as const,
    detail: (id: string) => ['docs', 'detail', id] as const,
    comments: (docId: string) => ['docs', 'comments', docId] as const,
    backlinks: (docId: string) => ['docs', 'backlinks', docId] as const,
  },
  drawings: {
    all: ['drawings'] as const,
    list: ['drawings', 'list'] as const,
    detail: (id: string) => ['drawings', 'detail', id] as const,
  },
  tasks: {
    all: ['tasks'] as const,
    list: (filters?: string) => ['tasks', 'list', filters] as const,
    detail: (id: string) => ['tasks', 'detail', id] as const,
    counts: ['tasks', 'counts'] as const,
    projects: ['tasks', 'projects'] as const,
    subtasks: (taskId: string) => ['tasks', 'subtasks', taskId] as const,
    activities: (taskId: string) => ['tasks', 'activities', taskId] as const,
    templates: ['tasks', 'templates'] as const,
  },
  hr: {
    all: ['hr'] as const,
    employees: {
      list: (filters?: string) => ['hr', 'employees', 'list', filters] as const,
      detail: (id: string) => ['hr', 'employees', 'detail', id] as const,
      counts: ['hr', 'employees', 'counts'] as const,
    },
    departments: {
      list: ['hr', 'departments', 'list'] as const,
      detail: (id: string) => ['hr', 'departments', 'detail', id] as const,
    },
    timeOff: {
      list: (filters?: string) => ['hr', 'timeOff', 'list', filters] as const,
      detail: (id: string) => ['hr', 'timeOff', 'detail', id] as const,
    },
    dashboard: ['hr', 'dashboard'] as const,
    leaveBalances: (employeeId: string) => ['hr', 'leave-balances', employeeId] as const,
    leaveBalancesSummary: ['hr', 'leave-balances', 'summary'] as const,
    onboarding: (employeeId: string) => ['hr', 'onboarding', employeeId] as const,
    onboardingTemplates: ['hr', 'onboarding-templates'] as const,
    documents: (employeeId: string) => ['hr', 'documents', employeeId] as const,
    leaveTypes: ['hr', 'leave-types'] as const,
    leavePolicies: ['hr', 'leave-policies'] as const,
    policyAssignment: (employeeId: string) => ['hr', 'policy-assignment', employeeId] as const,
    holidayCalendars: ['hr', 'holiday-calendars'] as const,
    holidays: (calendarId: string) => ['hr', 'holidays', calendarId] as const,
    workingDays: (start: string, end: string) => ['hr', 'working-days', start, end] as const,
    leaveApplications: (filters?: string) => ['hr', 'leave-applications', filters] as const,
    leaveCalendar: (month: string) => ['hr', 'leave-calendar', month] as const,
    pendingApprovals: ['hr', 'pending-approvals'] as const,
    attendance: (filters?: string) => ['hr', 'attendance', filters] as const,
    attendanceToday: ['hr', 'attendance', 'today'] as const,
    attendanceReport: (month: string) => ['hr', 'attendance-report', month] as const,
    employeeAttendance: (employeeId: string) => ['hr', 'employee-attendance', employeeId] as const,
    lifecycle: (employeeId: string) => ['hr', 'lifecycle', employeeId] as const,
  },
  tables: {
    all: ['tables'] as const,
    list: ['tables', 'list'] as const,
    detail: (id: string) => ['tables', 'detail', id] as const,
  },
  platform: {
    all: ['platform'] as const,
    tenants: ['platform', 'tenants'] as const,
    tenantUsers: (tenantId: string) => ['platform', 'tenant-users', tenantId] as const,
  },
  drive: {
    all: ['drive'] as const,
    items: (parentId?: string | null) => ['drive', 'items', parentId ?? 'root'] as const,
    detail: (id: string) => ['drive', 'detail', id] as const,
    breadcrumbs: (id: string) => ['drive', 'breadcrumbs', id] as const,
    favourites: ['drive', 'favourites'] as const,
    recent: ['drive', 'recent'] as const,
    trash: ['drive', 'trash'] as const,
    search: (q: string) => ['drive', 'search', q] as const,
    folders: ['drive', 'folders'] as const,
    storage: ['drive', 'storage'] as const,
    versions: (id: string) => ['drive', 'versions', id] as const,
    shareLinks: (id: string) => ['drive', 'shareLinks', id] as const,
    byType: (type: string) => ['drive', 'byType', type] as const,
  },
  admin: {
    all: ['admin'] as const,
    overview: ['admin', 'overview'] as const,
    tenants: ['admin', 'tenants'] as const,
    tenant: (id: string) => ['admin', 'tenant', id] as const,
  },
  sign: {
    all: ['sign'] as const,
    list: ['sign', 'list'] as const,
    detail: (id: string) => ['sign', 'detail', id] as const,
    fields: (docId: string) => ['sign', 'fields', docId] as const,
    tokens: (docId: string) => ['sign', 'tokens', docId] as const,
  },
  crm: {
    all: ['crm'] as const,
    contacts: {
      all: ['crm', 'contacts'] as const,
      detail: (id: string) => ['crm', 'contacts', id] as const,
    },
    companies: {
      all: ['crm', 'companies'] as const,
      detail: (id: string) => ['crm', 'companies', id] as const,
    },
    stages: ['crm', 'stages'] as const,
    deals: {
      all: ['crm', 'deals'] as const,
      detail: (id: string) => ['crm', 'deals', id] as const,
      counts: ['crm', 'deals', 'counts'] as const,
      pipeline: ['crm', 'deals', 'pipeline'] as const,
    },
    activities: {
      all: ['crm', 'activities'] as const,
    },
    workflows: {
      all: ['crm', 'workflows'] as const,
    },
    leads: {
      all: ['crm', 'leads'] as const,
      detail: (id: string) => ['crm', 'leads', id] as const,
    },
    notes: {
      all: ['crm', 'notes'] as const,
    },
    forecast: ['crm', 'forecast'] as const,
    dashboardCharts: ['crm', 'dashboard', 'charts'] as const,
    dashboard: ['crm', 'dashboard'] as const,
    permissions: {
      all: ['crm', 'permissions'] as const,
      me: ['crm', 'permissions', 'me'] as const,
    },
    google: {
      status: ['crm', 'google', 'status'] as const,
    },
    emails: {
      byContact: (id: string) => ['crm', 'emails', 'contact', id] as const,
      byDeal: (id: string) => ['crm', 'emails', 'deal', id] as const,
      byCompany: (id: string) => ['crm', 'emails', 'company', id] as const,
    },
    events: {
      byContact: (id: string) => ['crm', 'events', 'contact', id] as const,
      byDeal: (id: string) => ['crm', 'events', 'deal', id] as const,
    },
  },
  dataModel: {
    all: ['data-model'] as const,
    objects: ['data-model', 'objects'] as const,
    objectFields: (appId: string, objectId: string) => ['data-model', 'fields', appId, objectId] as const,
  },
};
