export const ROUTES = {
  SETUP: '/setup',
  LOGIN: '/login',
  INVITATION: '/invitation/:token',
  TENANT_USERS: '/settings/team',
  HOME: '/',
  SETTINGS: '/settings',
  DOCS: '/docs',
  DOC_DETAIL: '/docs/:id',
  DRAW: '/draw',
  DRAW_DETAIL: '/draw/:id',
  TASKS: '/tasks',
  TABLES: '/tables',
  TABLE_DETAIL: '/tables/:id',
  DRIVE: '/drive',
  DRIVE_FOLDER: '/drive/folder/:id',
  ORG: '/org',
  ORG_MEMBERS: '/org/members',
  ORG_APPS: '/org/apps',
  ORG_SETTINGS: '/org/settings',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
} as const;
