export const ROUTES = {
  LOGIN: '/login',
  AUTH_CALLBACK: '/auth/callback',
  HOME: '/',
  INBOX: '/mail',
  SENT: '/sent',
  DRAFTS: '/drafts',
  TRASH: '/trash',
  SEARCH: '/search',
  SETTINGS: '/settings',
  CALENDAR: '/calendar',
  DOCS: '/docs',
  DOC_DETAIL: '/docs/:id',
  DRAW: '/draw',
  DRAW_DETAIL: '/draw/:id',
  TASKS: '/tasks',
} as const;
