export const ROUTES = {
  SETUP: '/setup',
  LOGIN: '/login',
  INVITATION: '/invitation/:token',
  TENANT_USERS: '/settings/team',
  HOME: '/',
  SETTINGS: '/settings',
  DOCS: '/docs',
  DOC_DETAIL: '/docs/:id',
  DRAW: '/draw',
  DRAW_DETAIL: '/draw/:id',
  WORK: '/work',
  DRIVE: '/drive',
  DRIVE_FOLDER: '/drive/folder/:id',
  ORG: '/org',
  ORG_MEMBERS: '/org/members',
  ORG_MEMBER_EDIT: '/org/members/:userId',
  ORG_APPS: '/org/apps',
  ORG_SETTINGS: '/org/settings',
  CALENDAR: '/calendar',
  REGISTER: '/register',
  ONBOARDING: '/onboarding',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password/:token',
  CRM_AUTOMATION_EDIT: '/crm/automations/:id/edit',
} as const;
