import { useMemo } from 'react';
import { Quote } from 'lucide-react';
import type { WidgetDefinition, WidgetProps } from './types';

const QUOTES = [
  { text: 'The only way to do great work is to love what you do.', author: 'Steve Jobs' },
  { text: 'Innovation distinguishes between a leader and a follower.', author: 'Steve Jobs' },
  { text: 'Stay hungry, stay foolish.', author: 'Steve Jobs' },
  { text: 'Life is what happens when you\'re busy making other plans.', author: 'John Lennon' },
  { text: 'The future belongs to those who believe in the beauty of their dreams.', author: 'Eleanor Roosevelt' },
  { text: 'It is during our darkest moments that we must focus to see the light.', author: 'Aristotle' },
  { text: 'The purpose of our lives is to be happy.', author: 'Dalai Lama' },
  { text: 'Get busy living or get busy dying.', author: 'Stephen King' },
  { text: 'You only live once, but if you do it right, once is enough.', author: 'Mae West' },
  { text: 'The mind is everything. What you think you become.', author: 'Buddha' },
  { text: 'Strive not to be a success, but rather to be of value.', author: 'Albert Einstein' },
  { text: 'The best time to plant a tree was 20 years ago. The second best time is now.', author: 'Chinese Proverb' },
  { text: 'An unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Eighty percent of success is showing up.', author: 'Woody Allen' },
  { text: 'Your time is limited, don\'t waste it living someone else\'s life.', author: 'Steve Jobs' },
  { text: 'The only impossible journey is the one you never begin.', author: 'Tony Robbins' },
  { text: 'Believe you can and you\'re halfway there.', author: 'Theodore Roosevelt' },
  { text: 'Everything you\'ve ever wanted is on the other side of fear.', author: 'George Addair' },
  { text: 'We may encounter many defeats but we must not be defeated.', author: 'Maya Angelou' },
  { text: 'Knowing is not enough; we must apply. Wishing is not enough; we must do.', author: 'Johann Wolfgang von Goethe' },
  { text: 'Imagination is more important than knowledge.', author: 'Albert Einstein' },
  { text: 'Whether you think you can or you think you can\'t, you\'re right.', author: 'Henry Ford' },
  { text: 'I have not failed. I\'ve just found 10,000 ways that won\'t work.', author: 'Thomas Edison' },
  { text: 'A person who never made a mistake never tried anything new.', author: 'Albert Einstein' },
  { text: 'It does not matter how slowly you go as long as you do not stop.', author: 'Confucius' },
  { text: 'Success is not final, failure is not fatal: it is the courage to continue that counts.', author: 'Winston Churchill' },
  { text: 'Happiness is not something ready made. It comes from your own actions.', author: 'Dalai Lama' },
  { text: 'Well done is better than well said.', author: 'Benjamin Franklin' },
  { text: 'The only limit to our realization of tomorrow is our doubts of today.', author: 'Franklin D. Roosevelt' },
  { text: 'What lies behind us and what lies before us are tiny matters compared to what lies within us.', author: 'Ralph Waldo Emerson' },
  { text: 'Do what you can, with what you have, where you are.', author: 'Theodore Roosevelt' },
  { text: 'In the middle of every difficulty lies opportunity.', author: 'Albert Einstein' },
  { text: 'The best revenge is massive success.', author: 'Frank Sinatra' },
  { text: 'The secret of getting ahead is getting started.', author: 'Mark Twain' },
  { text: 'Don\'t watch the clock; do what it does. Keep going.', author: 'Sam Levenson' },
  { text: 'Try not to become a man of success. Rather become a man of value.', author: 'Albert Einstein' },
  { text: 'Great minds discuss ideas; average minds discuss events; small minds discuss people.', author: 'Eleanor Roosevelt' },
  { text: 'Those who dare to fail miserably can achieve greatly.', author: 'John F. Kennedy' },
  { text: 'The way to get started is to quit talking and begin doing.', author: 'Walt Disney' },
  { text: 'If you want to lift yourself up, lift up someone else.', author: 'Booker T. Washington' },
  { text: 'Simplicity is the ultimate sophistication.', author: 'Leonardo da Vinci' },
  { text: 'Act as if what you do makes a difference. It does.', author: 'William James' },
  { text: 'Nothing is impossible, the word itself says I\'m possible!', author: 'Audrey Hepburn' },
  { text: 'The best way to predict the future is to create it.', author: 'Peter Drucker' },
  { text: 'Keep your face always toward the sunshine and shadows will fall behind you.', author: 'Walt Whitman' },
  { text: 'What we achieve inwardly will change outer reality.', author: 'Plutarch' },
  { text: 'Quality is not an act, it is a habit.', author: 'Aristotle' },
  { text: 'If you can dream it, you can do it.', author: 'Walt Disney' },
  { text: 'You miss 100% of the shots you don\'t take.', author: 'Wayne Gretzky' },
  { text: 'Every moment is a fresh beginning.', author: 'T.S. Eliot' },
  { text: 'The only person you are destined to become is the person you decide to be.', author: 'Ralph Waldo Emerson' },
  { text: 'Courage is not the absence of fear, but the triumph over it.', author: 'Nelson Mandela' },
  { text: 'What you do speaks so loudly that I cannot hear what you say.', author: 'Ralph Waldo Emerson' },
  { text: 'Turn your wounds into wisdom.', author: 'Oprah Winfrey' },
  { text: 'Life shrinks or expands in proportion to one\'s courage.', author: 'Anais Nin' },
  { text: 'Change is the law of life. Those who look only to the past are certain to miss the future.', author: 'John F. Kennedy' },
  { text: 'The greatest glory in living lies not in never falling, but in rising every time we fall.', author: 'Nelson Mandela' },
  { text: 'In three words I can sum up everything I\'ve learned about life: it goes on.', author: 'Robert Frost' },
  { text: 'Life is really simple, but we insist on making it complicated.', author: 'Confucius' },
  { text: 'Never let the fear of striking out keep you from playing the game.', author: 'Babe Ruth' },
  { text: 'The unexamined life is not worth living.', author: 'Socrates' },
  { text: 'Go confidently in the direction of your dreams. Live the life you have imagined.', author: 'Henry David Thoreau' },
  { text: 'You must be the change you wish to see in the world.', author: 'Mahatma Gandhi' },
  { text: 'The journey of a thousand miles begins with one step.', author: 'Lao Tzu' },
  { text: 'That which does not kill us makes us stronger.', author: 'Friedrich Nietzsche' },
  { text: 'Love the life you live. Live the life you love.', author: 'Bob Marley' },
  { text: 'Not how long, but how well you have lived is the main thing.', author: 'Seneca' },
  { text: 'Dream big and dare to fail.', author: 'Norman Vaughan' },
  { text: 'Spread love everywhere you go.', author: 'Mother Teresa' },
  { text: 'When you reach the end of your rope, tie a knot in it and hang on.', author: 'Franklin D. Roosevelt' },
  { text: 'If you look at what you have in life, you\'ll always have more.', author: 'Oprah Winfrey' },
  { text: 'Always remember that you are absolutely unique. Just like everyone else.', author: 'Margaret Mead' },
  { text: 'The power of imagination makes us infinite.', author: 'John Muir' },
  { text: 'Creativity is intelligence having fun.', author: 'Albert Einstein' },
  { text: 'Live as if you were to die tomorrow. Learn as if you were to live forever.', author: 'Mahatma Gandhi' },
  { text: 'The only way out is through.', author: 'Robert Frost' },
  { text: 'To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.', author: 'Ralph Waldo Emerson' },
  { text: 'Perfection is not attainable, but if we chase perfection we can catch excellence.', author: 'Vince Lombardi' },
  { text: 'Be yourself; everyone else is already taken.', author: 'Oscar Wilde' },
  { text: 'Two things are infinite: the universe and human stupidity; and I\'m not sure about the universe.', author: 'Albert Einstein' },
  { text: 'The only true wisdom is in knowing you know nothing.', author: 'Socrates' },
  { text: 'Without music, life would be a mistake.', author: 'Friedrich Nietzsche' },
  { text: 'We accept the love we think we deserve.', author: 'Stephen Chbosky' },
  { text: 'I think, therefore I am.', author: 'Rene Descartes' },
  { text: 'To live is the rarest thing in the world. Most people exist, that is all.', author: 'Oscar Wilde' },
  { text: 'In the end, we will remember not the words of our enemies, but the silence of our friends.', author: 'Martin Luther King Jr.' },
  { text: 'The greatest wealth is to live content with little.', author: 'Plato' },
  { text: 'Wisely and slow; they stumble that run fast.', author: 'William Shakespeare' },
  { text: 'He who has a why to live can bear almost any how.', author: 'Friedrich Nietzsche' },
  { text: 'No one can make you feel inferior without your consent.', author: 'Eleanor Roosevelt' },
  { text: 'Dost thou love life? Then do not squander time, for that is the stuff life is made of.', author: 'Benjamin Franklin' },
  { text: 'Education is the most powerful weapon which you can use to change the world.', author: 'Nelson Mandela' },
  { text: 'All that we are is the result of what we have thought.', author: 'Buddha' },
  { text: 'We are what we repeatedly do. Excellence, then, is not an act, but a habit.', author: 'Aristotle' },
  { text: 'Only a life lived for others is a life worthwhile.', author: 'Albert Einstein' },
  { text: 'Where there is love there is life.', author: 'Mahatma Gandhi' },
  { text: 'The mind is its own place, and in itself can make a heaven of hell, a hell of heaven.', author: 'John Milton' },
  { text: 'I cannot teach anybody anything. I can only make them think.', author: 'Socrates' },
  { text: 'Time you enjoy wasting is not wasted time.', author: 'Marthe Troly-Curtin' },
  { text: 'A room without books is like a body without a soul.', author: 'Marcus Tullius Cicero' },
  { text: 'The fool doth think he is wise, but the wise man knows himself to be a fool.', author: 'William Shakespeare' },
  { text: 'If you tell the truth, you don\'t have to remember anything.', author: 'Mark Twain' },
  { text: 'Life is what we make it, always has been, always will be.', author: 'Grandma Moses' },
  { text: 'Success usually comes to those who are too busy to be looking for it.', author: 'Henry David Thoreau' },
  { text: 'Don\'t count the days, make the days count.', author: 'Muhammad Ali' },
  { text: 'The harder I work, the luckier I get.', author: 'Samuel Goldwyn' },
  { text: 'Everything has beauty, but not everyone sees it.', author: 'Confucius' },
  { text: 'If opportunity doesn\'t knock, build a door.', author: 'Milton Berle' },
  { text: 'The only thing we have to fear is fear itself.', author: 'Franklin D. Roosevelt' },
  { text: 'Whoever is happy will make others happy too.', author: 'Anne Frank' },
  { text: 'Hope is a waking dream.', author: 'Aristotle' },
  { text: 'It always seems impossible until it\'s done.', author: 'Nelson Mandela' },
  { text: 'Difficulties strengthen the mind, as labor does the body.', author: 'Seneca' },
  { text: 'Genius is one percent inspiration and ninety-nine percent perspiration.', author: 'Thomas Edison' },
  { text: 'What we know is a drop, what we don\'t know is an ocean.', author: 'Isaac Newton' },
  { text: 'Begin at the beginning and go on till you come to the end: then stop.', author: 'Lewis Carroll' },
  { text: 'A journey of a thousand miles must begin with a single step.', author: 'Lao Tzu' },
  { text: 'Problems are not stop signs, they are guidelines.', author: 'Robert H. Schuller' },
  { text: 'The best way out is always through.', author: 'Robert Frost' },
  { text: 'You can never cross the ocean until you have the courage to lose sight of the shore.', author: 'Christopher Columbus' },
  { text: 'Life is 10% what happens to you and 90% how you react to it.', author: 'Charles R. Swindoll' },
  { text: 'It is never too late to be what you might have been.', author: 'George Eliot' },
  { text: 'Happiness depends upon ourselves.', author: 'Aristotle' },
  { text: 'I find that the harder I work, the more luck I seem to have.', author: 'Thomas Jefferson' },
  { text: 'The world breaks everyone, and afterward, some are strong at the broken places.', author: 'Ernest Hemingway' },
  { text: 'The only thing standing between you and your goal is the story you keep telling yourself.', author: 'Jordan Belfort' },
  { text: 'We become what we think about.', author: 'Earl Nightingale' },
  { text: 'The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.', author: 'Winston Churchill' },
  { text: 'Things do not happen. Things are made to happen.', author: 'John F. Kennedy' },
  { text: 'Nothing will work unless you do.', author: 'Maya Angelou' },
  { text: 'Don\'t be afraid to give up the good to go for the great.', author: 'John D. Rockefeller' },
  { text: 'All our dreams can come true, if we have the courage to pursue them.', author: 'Walt Disney' },
  { text: 'With the new day comes new strength and new thoughts.', author: 'Eleanor Roosevelt' },
  { text: 'Optimism is the faith that leads to achievement.', author: 'Helen Keller' },
  { text: 'Do one thing every day that scares you.', author: 'Eleanor Roosevelt' },
  { text: 'Failure is the condiment that gives success its flavor.', author: 'Truman Capote' },
  { text: 'A champion is defined not by their wins but by how they can recover when they fall.', author: 'Serena Williams' },
  { text: 'The only real mistake is the one from which we learn nothing.', author: 'Henry Ford' },
  { text: 'It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.', author: 'Charles Darwin' },
  { text: 'The best preparation for tomorrow is doing your best today.', author: 'H. Jackson Brown Jr.' },
  { text: 'There is nothing permanent except change.', author: 'Heraclitus' },
  { text: 'Logic will get you from A to Z; imagination will get you everywhere.', author: 'Albert Einstein' },
  { text: 'Start where you are. Use what you have. Do what you can.', author: 'Arthur Ashe' },
  { text: 'If you want something you\'ve never had, you must be willing to do something you\'ve never done.', author: 'Thomas Jefferson' },
  { text: 'Don\'t let yesterday take up too much of today.', author: 'Will Rogers' },
  { text: 'People who are crazy enough to think they can change the world are the ones who do.', author: 'Rob Siltanen' },
  { text: 'You are never too old to set another goal or to dream a new dream.', author: 'C.S. Lewis' },
  { text: 'How wonderful it is that nobody need wait a single moment before starting to improve the world.', author: 'Anne Frank' },
  { text: 'The creation of a thousand forests is in one acorn.', author: 'Ralph Waldo Emerson' },
  { text: 'Setting goals is the first step in turning the invisible into the visible.', author: 'Tony Robbins' },
  { text: 'What you get by achieving your goals is not as important as what you become by achieving your goals.', author: 'Zig Ziglar' },
  { text: 'Hardships often prepare ordinary people for an extraordinary destiny.', author: 'C.S. Lewis' },
  { text: 'Motivation is what gets you started. Habit is what keeps you going.', author: 'Jim Ryun' },
  { text: 'Small deeds done are better than great deeds planned.', author: 'Peter Marshall' },
  { text: 'The future depends on what you do today.', author: 'Mahatma Gandhi' },
  { text: 'Luck is a dividend of sweat. The more you sweat, the luckier you get.', author: 'Ray Kroc' },
  { text: 'Don\'t be pushed around by the fears in your mind. Be led by the dreams in your heart.', author: 'Roy T. Bennett' },
  { text: 'Success is walking from failure to failure with no loss of enthusiasm.', author: 'Winston Churchill' },
  { text: 'Opportunities don\'t happen. You create them.', author: 'Chris Grosser' },
  { text: 'I am not a product of my circumstances. I am a product of my decisions.', author: 'Stephen Covey' },
  { text: 'Your limitation—it\'s only your imagination.', author: 'Unknown' },
  { text: 'Great things never come from comfort zones.', author: 'Unknown' },
  { text: 'Push yourself, because no one else is going to do it for you.', author: 'Unknown' },
  { text: 'Sometimes later becomes never. Do it now.', author: 'Unknown' },
  { text: 'Wake up with determination. Go to bed with satisfaction.', author: 'Unknown' },
  { text: 'Little things make big days.', author: 'Unknown' },
  { text: 'It\'s going to be hard, but hard does not mean impossible.', author: 'Unknown' },
  { text: 'Don\'t stop when you\'re tired. Stop when you\'re done.', author: 'Unknown' },
  { text: 'The key to success is to focus on goals, not obstacles.', author: 'Unknown' },
  { text: 'Dream it. Wish it. Do it.', author: 'Unknown' },
  { text: 'Doubt kills more dreams than failure ever will.', author: 'Suzy Kassem' },
  { text: 'Work hard in silence, let your success be your noise.', author: 'Frank Ocean' },
  { text: 'If it doesn\'t challenge you, it doesn\'t change you.', author: 'Fred DeVito' },
  { text: 'What seems to us as bitter trials are often blessings in disguise.', author: 'Oscar Wilde' },
  { text: 'Success is not in what you have, but who you are.', author: 'Bo Bennett' },
  { text: 'Fall seven times and stand up eight.', author: 'Japanese Proverb' },
  { text: 'The struggle you\'re in today is developing the strength you need for tomorrow.', author: 'Robert Tew' },
  { text: 'Don\'t wish it were easier. Wish you were better.', author: 'Jim Rohn' },
  { text: 'Hustle until you no longer need to introduce yourself.', author: 'Unknown' },
  { text: 'Discipline is the bridge between goals and accomplishment.', author: 'Jim Rohn' },
  { text: 'Formal education will make you a living; self-education will make you a fortune.', author: 'Jim Rohn' },
  { text: 'Don\'t limit your challenges. Challenge your limits.', author: 'Unknown' },
  { text: 'The difference between ordinary and extraordinary is that little extra.', author: 'Jimmy Johnson' },
  { text: 'Focus on being productive instead of busy.', author: 'Tim Ferriss' },
  { text: 'You don\'t have to be great to start, but you have to start to be great.', author: 'Zig Ziglar' },
];

function getDailyQuoteIndex(): number {
  const now = new Date();
  const seed = now.getFullYear() * 10000 + (now.getMonth() + 1) * 100 + now.getDate();
  return seed % QUOTES.length;
}

function QuoteWidgetComponent({ width, height }: WidgetProps) {
  const quote = useMemo(() => QUOTES[getDailyQuoteIndex()], []);

  return (
    <div
      style={{
        width,
        height,
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        padding: '8px 10px',
        overflow: 'hidden',
      }}
    >
      <p
        style={{
          color: '#fff',
          fontSize: 9,
          lineHeight: 1.3,
          margin: 0,
          overflow: 'hidden',
          display: '-webkit-box',
          WebkitLineClamp: 3,
          WebkitBoxOrient: 'vertical',
          fontStyle: 'italic',
          opacity: 0.9,
        }}
      >
        "{quote.text}"
      </p>
      <span
        style={{
          color: 'rgba(255,255,255,0.6)',
          fontSize: 8,
          marginTop: 4,
          fontWeight: 500,
        }}
      >
        — {quote.author}
      </span>
    </div>
  );
}

export const quoteWidget: WidgetDefinition = {
  id: 'quote',
  name: 'Quote of the day',
  description: 'Daily inspirational quote from a curated collection',
  icon: Quote,
  defaultEnabled: true,
  component: QuoteWidgetComponent,
};
