import os from 'node:os';
import type { MarketplaceManifest, MarketplaceServiceDef } from './types';

/**
 * Get the Docker platform string for this host (e.g. linux/amd64, linux/arm64).
 */
export function getHostPlatform(): string {
  const arch = os.arch(); // 'arm64', 'x64', etc.
  const platformArch = arch === 'x64' ? 'amd64' : arch === 'arm64' ? 'arm64' : arch;
  return `linux/${platformArch}`;
}

/**
 * Resolve the correct Docker image for a service based on host platform.
 * Uses platformImages override if available, otherwise falls back to the default image.
 */
function resolveImage(service: MarketplaceServiceDef): string {
  if (service.platformImages) {
    const platform = getHostPlatform();
    const override = service.platformImages[platform];
    if (override) return override;
  }
  return service.image;
}

/**
 * Generates a docker-compose.yml string from a marketplace app manifest.
 *
 * Variable replacement:
 *  - $SECRET_<name>_<length> → actual secret value from the secrets map
 *  - $ASSIGNED_PORT → the externally mapped port
 *  - $APP_URL → http://hostname:port
 */
export function generateComposeFile(
  manifest: MarketplaceManifest,
  assignedPort: number,
  secrets: Record<string, string>,
  hostname: string = 'localhost',
): string {
  const appUrl = `http://${hostname}:${assignedPort}`;
  const lines: string[] = [];

  lines.push(`# Auto-generated by Atlas Marketplace — do not edit`);
  lines.push(`name: atlas_${manifest.id}`);
  lines.push('');
  lines.push('services:');

  // Collect all volume names for the volumes section
  const allVolumes: Set<string> = new Set();

  for (const [serviceName, service] of Object.entries(manifest.services)) {
    lines.push(`  ${serviceName}:`);
    lines.push(`    image: ${resolveImage(service)}`);

    // Custom entrypoint
    if (service.entrypoint) {
      lines.push(`    entrypoint: ${yamlQuote(service.entrypoint)}`);
    }

    // Custom command
    if (service.command && service.command.length > 0) {
      lines.push(`    command: ${JSON.stringify(service.command)}`);
    }

    // Only the "app" service gets the external port mapping
    if (service.port) {
      lines.push(`    ports:`);
      lines.push(`      - "${assignedPort}:${service.port}"`);
    }

    // Environment variables
    if (service.env && Object.keys(service.env).length > 0) {
      lines.push(`    environment:`);
      for (const [key, rawValue] of Object.entries(service.env)) {
        const resolvedValue = resolveValue(rawValue, secrets, assignedPort, appUrl);
        lines.push(`      ${key}: ${yamlQuote(resolvedValue)}`);
      }
    }

    // Volumes
    if (service.volumes && service.volumes.length > 0) {
      lines.push(`    volumes:`);
      for (const vol of service.volumes) {
        const [volName, mountPath] = vol.split(':');
        const prefixedName = `${volName}`;
        allVolumes.add(prefixedName);
        lines.push(`      - ${prefixedName}:${mountPath}`);
      }
    }

    // depends_on with health condition
    if (service.dependsOn && service.dependsOn.length > 0) {
      lines.push(`    depends_on:`);
      for (const dep of service.dependsOn) {
        const depService = manifest.services[dep];
        if (depService?.healthCheck) {
          lines.push(`      ${dep}:`);
          lines.push(`        condition: service_healthy`);
        } else {
          lines.push(`      ${dep}:`);
          lines.push(`        condition: service_started`);
        }
      }
    }

    // Health check — only add explicit healthcheck for non-HTTP services
    // (ones with a shell command, not an HTTP path)
    if (service.healthCheck && !service.healthCheck.startsWith('/')) {
      const parts = parseHealthCheckCommand(service.healthCheck);
      lines.push(`    healthcheck:`);
      lines.push(`      test: ${JSON.stringify(['CMD', ...parts])}`);
      lines.push(`      interval: 10s`);
      lines.push(`      timeout: 5s`);
      lines.push(`      retries: 5`);
    }

    lines.push(`    restart: unless-stopped`);
    lines.push('');
  }

  // Named volumes section
  if (allVolumes.size > 0) {
    lines.push('volumes:');
    for (const vol of allVolumes) {
      lines.push(`  ${vol}:`);
      lines.push(`    name: atlas_${manifest.id}_${vol}`);
    }
    lines.push('');
  }

  // Network
  lines.push('networks:');
  lines.push('  default:');
  lines.push(`    name: atlas_${manifest.id}_net`);
  lines.push('');

  return lines.join('\n');
}

/**
 * Replace $SECRET_<name>_<length>, $ASSIGNED_PORT, and $APP_URL placeholders
 * in environment variable values.
 */
function resolveValue(
  raw: string,
  secrets: Record<string, string>,
  assignedPort: number,
  appUrl: string,
): string {
  let result = raw;

  // Replace $APP_URL
  result = result.replace(/\$APP_URL/g, appUrl);

  // Replace $ASSIGNED_PORT
  result = result.replace(/\$ASSIGNED_PORT/g, String(assignedPort));

  // Replace $SECRET_<name>_<length> patterns
  result = result.replace(/\$SECRET_([A-Z0-9_]+)_(\d+)/g, (_match, name, length) => {
    const secretKey = `SECRET_${name}_${length}`;
    return secrets[secretKey] ?? `MISSING_SECRET_${secretKey}`;
  });

  return result;
}

/**
 * Parse a health check command string into an array of arguments.
 * Handles simple quoted strings and space-separated tokens.
 */
function parseHealthCheckCommand(cmd: string): string[] {
  const parts: string[] = [];
  let current = '';
  let inQuote = false;
  let quoteChar = '';

  for (const ch of cmd) {
    if (inQuote) {
      if (ch === quoteChar) {
        inQuote = false;
      } else {
        current += ch;
      }
    } else if (ch === '"' || ch === "'") {
      inQuote = true;
      quoteChar = ch;
    } else if (ch === ' ') {
      if (current.length > 0) {
        parts.push(current);
        current = '';
      }
    } else {
      current += ch;
    }
  }

  if (current.length > 0) {
    parts.push(current);
  }

  return parts;
}

/**
 * Quote a YAML value if it contains special characters.
 */
function yamlQuote(value: string): string {
  // If value contains characters that need quoting in YAML
  if (
    value.includes(':') ||
    value.includes('#') ||
    value.includes('{') ||
    value.includes('}') ||
    value.includes('[') ||
    value.includes(']') ||
    value.includes(',') ||
    value.includes('&') ||
    value.includes('*') ||
    value.includes('?') ||
    value.includes('|') ||
    value.includes('>') ||
    value.includes('!') ||
    value.includes('%') ||
    value.includes('@') ||
    value.includes('`') ||
    value.startsWith("'") ||
    value.startsWith('"')
  ) {
    // Use double quotes and escape internal double quotes
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return value;
}
