import { appRegistry } from '../config/app-registry';
import { crmManifest } from './crm/manifest';
import { hrManifest } from './hr/manifest';
import { calendarManifest } from './calendar/manifest';
import { projectsManifest } from './projects/manifest';
import { signManifest } from './sign/manifest';
import { driveManifest } from './drive/manifest';
import { tablesManifest } from './tables/manifest';
import { tasksManifest } from './tasks/manifest';
import { docsManifest } from './docs/manifest';
import { drawManifest } from './draw/manifest';
import { invoicesManifest } from './invoices/manifest';
import { systemManifest } from './system/manifest';
appRegistry.register(crmManifest);
appRegistry.register(hrManifest);
appRegistry.register(calendarManifest);
appRegistry.register(projectsManifest);
appRegistry.register(signManifest);
appRegistry.register(driveManifest);
appRegistry.register(tablesManifest);
appRegistry.register(tasksManifest);
appRegistry.register(docsManifest);
appRegistry.register(drawManifest);
appRegistry.register(invoicesManifest);
appRegistry.register(systemManifest);

export { appRegistry };
