// Re-export ported task handlers
export {
  listTasks,
  createTask,
  searchTasks,
  getTaskCounts,
  getTask,
  updateTask,
  deleteTask,
  reorderTasks,
  listSubtasks,
  createSubtask,
  updateSubtask,
  deleteSubtask,
  reorderSubtasks,
  listActivities,
  listTemplates,
  createTemplate,
  updateTemplate,
  deleteTemplate,
  createTaskFromTemplate,
  listComments,
  createComment,
  deleteComment,
  listAttachments,
  uploadAttachment,
  deleteAttachment,
  downloadAttachment,
  listDependencies,
  addDependency,
  removeDependency,
  getBlockedTaskIds,
  updateTaskVisibility,
} from './controllers/tasks.controller';

// Re-export ported project handlers
export {
  getDashboard,
  listProjects,
  createProject,
  getProject,
  updateProject,
  deleteProject,
  listProjectMembers,
  addProjectMember,
  removeProjectMember,
  updateProjectMemberRate,
  listProjectTimeEntries,
  createProjectTimeEntry,
  updateProjectTimeEntry,
  deleteProjectTimeEntry,
  listProjectFiles,
  addProjectFile,
  removeProjectFile,
  getProjectFinancials,
  listTimeEntries,
  createTimeEntry,
  updateTimeEntry,
  deleteTimeEntry,
  previewTimeBilling,
  populateFromTimeBilling,
} from './controllers/projects.controller';

// Re-export settings handlers (tenant-wide, admin-gated)
export {
  getSettings as getWorkSettings,
  updateSettings as updateWorkSettings,
} from './controllers/settings.controller';
