import { z } from 'zod';

export const loginSchema = z.object({
  code: z.string().min(1),
  redirectUri: z.string().url(),
});

export const searchSchema = z.object({
  q: z.string().min(1).max(500),
  from: z.string().optional(),
  to: z.string().optional(),
  after: z.string().optional(),
  before: z.string().optional(),
  hasAttachment: z.boolean().optional(),
  category: z.string().optional(),
});

export const composeSchema = z.object({
  to: z.array(z.string().email()).min(1),
  cc: z.array(z.string().email()).optional(),
  bcc: z.array(z.string().email()).optional(),
  subject: z.string().max(500).optional(),
  bodyHtml: z.string(),
  bodyText: z.string().optional(),
  threadId: z.string().optional(),
  inReplyTo: z.string().optional(),
  trackingEnabled: z.boolean().optional(),
});

export const settingsSchema = z.object({
  theme: z.enum(['light', 'dark', 'system']).optional(),
  density: z.enum(['compact', 'default', 'comfortable']).optional(),
  readingPane: z.enum(['right', 'bottom', 'hidden']).optional(),
  autoAdvance: z.enum(['next', 'previous', 'list']).optional(),
  desktopNotifications: z.boolean().optional(),
  notificationSound: z.boolean().optional(),
  signatureHtml: z.string().nullable().optional(),
  trackingEnabled: z.boolean().optional(),
  // Tasks settings
  tasksDefaultView: z.enum(['inbox', 'today', 'anytime']).optional(),
  tasksConfirmDelete: z.boolean().optional(),
  tasksShowCalendar: z.boolean().optional(),
  tasksShowEvening: z.boolean().optional(),
  tasksShowWhenBadges: z.boolean().optional(),
  tasksShowProject: z.boolean().optional(),
  tasksShowNotesIndicator: z.boolean().optional(),
  tasksCompactMode: z.boolean().optional(),
  tasksCompletedBehavior: z.enum(['fade', 'move', 'hide']).optional(),
  tasksDefaultSort: z.enum(['manual', 'priority', 'dueDate', 'title', 'created']).optional(),
  tasksViewMode: z.enum(['list', 'board']).optional(),
  // Global settings
  dateFormat: z.enum(['MM/DD/YYYY', 'DD/MM/YYYY', 'YYYY-MM-DD']).optional(),
  currencySymbol: z.string().max(5).optional(),
  timezone: z.string().max(100).optional(),
  timeFormat: z.enum(['12h', '24h']).optional(),
  numberFormat: z.enum(['comma-period', 'period-comma', 'space-comma']).optional(),
  calendarStartDay: z.enum(['sunday', 'monday']).optional(),
  // Tables settings
  tablesDefaultView: z.enum(['grid', 'kanban', 'calendar', 'gallery']).optional(),
  tablesDefaultSort: z.enum(['none', 'createdDate', 'alphabetical']).optional(),
  tablesShowFieldTypeIcons: z.boolean().optional(),
  tablesDefaultRowCount: z.number().int().min(0).max(100).optional(),
  tablesIncludeRowIdsInExport: z.boolean().optional(),
  // Calendar settings
  calDefaultView: z.enum(['week', 'month-grid', 'day', 'agenda', 'year']).optional(),
  calWeekStartsOnMonday: z.boolean().optional(),
  calShowWeekNumbers: z.boolean().optional(),
  calDensity: z.enum(['compact', 'default', 'comfortable']).optional(),
  calWorkStartHour: z.number().int().min(0).max(23).optional(),
  calWorkEndHour: z.number().int().min(0).max(23).optional(),
  calSecondaryTimezone: z.string().max(100).nullable().optional(),
  calEventReminderMinutes: z.number().int().min(0).max(1440).optional(),
  // General app settings
  language: z.string().max(10).optional(),
  fontFamily: z.enum(['inter', 'geist', 'system', 'roboto', 'open-sans', 'lato']).optional(),
  colorTheme: z.enum(['default', 'ocean', 'forest', 'sunset', 'rose', 'lavender', 'amber', 'slate']).optional(),
  showBadgeCount: z.boolean().optional(),
  notificationLevel: z.enum(['all', 'smart', 'priority', 'none']).optional(),
  composeMode: z.enum(['plain', 'rich']).optional(),
  signature: z.string().optional(),
  includeSignatureInReplies: z.boolean().optional(),
  undoSendDelay: z.union([z.literal(5), z.literal(10), z.literal(20), z.literal(30)]).optional(),
  sendAnimation: z.boolean().optional(),
  themeTransition: z.boolean().optional(),
  customShortcuts: z.record(z.string()).optional(),
  // AI settings
  aiEnabled: z.boolean().optional(),
  aiProvider: z.string().max(50).optional(),
  aiApiKeys: z.record(z.string()).optional(),
  aiCustomProvider: z.record(z.string()).optional(),
  aiWritingAssistant: z.boolean().optional(),
  aiQuickReplies: z.boolean().optional(),
  aiThreadSummary: z.boolean().optional(),
  aiTranslation: z.boolean().optional(),
  // Docs settings
  docsFontStyle: z.enum(['default', 'serif', 'mono']).optional(),
  docsSmallText: z.boolean().optional(),
  docsFullWidth: z.boolean().optional(),
  docsSpellCheck: z.boolean().optional(),
  docsOpenLastVisited: z.boolean().optional(),
  docsSidebarDefault: z.enum(['tree', 'favorites', 'recent']).optional(),
  docFavorites: z.array(z.string()).optional(),
  docRecent: z.array(z.string()).optional(),
  // Draw settings
  drawGridMode: z.boolean().optional(),
  drawSnapToGrid: z.boolean().optional(),
  drawDefaultBackground: z.enum(['white', 'light', 'dark']).optional(),
  drawExportQuality: z.union([z.literal(1), z.literal(2), z.literal(4)]).optional(),
  drawExportWithBackground: z.boolean().optional(),
  drawAutoSaveInterval: z.union([z.literal(1000), z.literal(2000), z.literal(5000), z.literal(10000)]).optional(),
  drawSortOrder: z.enum(['name', 'created', 'modified']).optional(),
  drawLibrary: z.array(z.unknown()).optional(),
  // Drive settings
  driveDefaultView: z.enum(['list', 'grid']).optional(),
  driveDefaultSort: z.enum(['default', 'name', 'size', 'date', 'type']).optional(),
  driveSidebarDefault: z.enum(['files', 'favourites', 'recent']).optional(),
  driveShowPreviewPanel: z.boolean().optional(),
  driveCompactMode: z.boolean().optional(),
  driveConfirmDelete: z.boolean().optional(),
  driveAutoVersionOnReplace: z.boolean().optional(),
  driveMaxVersions: z.union([z.literal(5), z.literal(10), z.literal(20), z.literal(50)]).optional(),
  driveShareDefaultExpiry: z.enum(['never', '1', '7', '30']).optional(),
  driveDuplicateHandling: z.enum(['rename', 'replace', 'ask']).optional(),
  driveShowThumbnails: z.boolean().optional(),
  driveShowFileExtensions: z.boolean().optional(),
  driveSortOrder: z.enum(['asc', 'desc']).optional(),
  // Home background settings
  homeBgType: z.enum(['unsplash', 'solid', 'gradient', 'custom']).optional(),
  homeBgValue: z.string().max(1000).nullable().optional(),
  homeShowSeconds: z.boolean().optional(),
  // Home widget settings
  homeEnabledWidgets: z.array(z.string()).nullable().optional(),
  // App widget settings
  appWidgets: z.record(z.object({
    enabledIds: z.array(z.string()),
    order: z.array(z.string()),
  })).nullable().optional(),
  // Search
  recentSearches: z.array(z.string()).optional(),
});
